"""Initial migration - SQLite

Revision ID: 5cda3fab67c6
Revises: 
Create Date: 2025-11-05 10:18:32.011793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cda3fab67c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('selected_symptoms', sa.PickleType(), nullable=True),
    sa.Column('cf_values', sa.PickleType(), nullable=True),
    sa.Column('final_cf_value', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('certainty_level', sa.String(length=30), nullable=True),
    sa.Column('matched_rule_id', sa.Integer(), nullable=True),
    sa.Column('forward_chaining_result', sa.PickleType(), nullable=True),
    sa.Column('ai_solution', sa.Text(), nullable=True),
    sa.Column('ai_solution_json', sa.PickleType(), nullable=True),
    sa.Column('diagnosis_method', sa.String(length=20), nullable=True),
    sa.Column('diagnosis_date', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['matched_rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_history_diagnosis_date'), ['diagnosis_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_history_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_history_expires_at'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_history_diagnosis_date'))

    op.drop_table('diagnosis_history')
    # ### end Alembic commands ###
